// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import FaceLanding from '@/components/live/FaceLanding';

export default function Page() {
  return <FaceLanding signIn="/admin/adm-01-sign-in" home="/admin/adm-02-overview" />;
}
