// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import Screen from '@/screens/dsp-34-reset-access';

export const metadata: Metadata = { title: "DSP-34 Reset access · Lodestar Plan" };

const nav = {
  "links": {
    "L175": {
      "href": "/plan/dsp-06-sign-in",
      "kind": "go"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P2" nav={nav}>
      <Screen />
    </ScreenShell>
  );
}
