apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: planning
  labels:
    app: planning
    app.kubernetes.io/name: planning
    app.kubernetes.io/part-of: lodestar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: planning
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
