apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: planning
  labels:
    app: planning
    app.kubernetes.io/name: planning
    app.kubernetes.io/part-of: lodestar
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: planning
