apiVersion: v1
kind: Service
metadata:
  name: planning
  labels:
    app: planning
    app.kubernetes.io/name: planning
    app.kubernetes.io/part-of: lodestar
spec:
  type: ClusterIP
  selector:
    app: planning
  ports:
  - name: http
    port: 3003
    targetPort: http
    protocol: TCP
    appProtocol: http
