apiVersion: v1
kind: ServiceAccount
metadata:
  name: planning
  labels:
    app: planning
    app.kubernetes.io/name: planning
    app.kubernetes.io/part-of: lodestar
  annotations:
    azure.workload.identity/client-id: CLIENT_ID_PLANNING
    azure.workload.identity/tenant-id: TENANT_ID
automountServiceAccountToken: false
