// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import LiveSwitch from '@/components/live/LiveSwitch';
import Screen from '@/screens/sm-35-reset-access';
import Live from '@/live/sm-35-reset-access';

export const metadata: Metadata = { title: "SM-35 Reset access · Lodestar Store" };

const nav = {
  "links": {
    "L140": {
      "href": "/store/sm-02-deliveries",
      "kind": "go"
    },
    "L141": {
      "href": "/store/sm-26-sign-in",
      "kind": "go"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P1" nav={nav} live>
      <LiveSwitch live={<Live />}>
        <Screen />
      </LiveSwitch>
    </ScreenShell>
  );
}
