// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import LiveSwitch from '@/components/live/LiveSwitch';
import Screen from '@/screens/dsp-07-2-step-verification';
import Live from '@/live/dsp-07-2-step-verification';

export const metadata: Metadata = { title: "DSP-07 2-step verification · Lodestar Plan" };

const nav = {
  "links": {
    "L146": {
      "href": "/plan/dsp-08-today-overview",
      "kind": "go"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P2" nav={nav} live>
      <LiveSwitch live={<Live />}>
        <Screen />
      </LiveSwitch>
    </ScreenShell>
  );
}
