// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import { Inter_400Regular, Inter_400Regular_Italic, Inter_500Medium, Inter_600SemiBold, Inter_700Bold, Inter_800ExtraBold } from '@expo-google-fonts/inter';
import { JetBrainsMono_600SemiBold, JetBrainsMono_700Bold } from '@expo-google-fonts/jetbrains-mono';
import { NotoSansSinhala_400Regular, NotoSansSinhala_600SemiBold, NotoSansSinhala_700Bold, NotoSansSinhala_800ExtraBold } from '@expo-google-fonts/noto-sans-sinhala';
import { NotoSansTamil_600SemiBold, NotoSansTamil_700Bold, NotoSansTamil_800ExtraBold } from '@expo-google-fonts/noto-sans-tamil';
import { PlusJakartaSans_700Bold, PlusJakartaSans_800ExtraBold } from '@expo-google-fonts/plus-jakarta-sans';

export const FONTS = { Inter_400Regular, Inter_400Regular_Italic, Inter_500Medium, Inter_600SemiBold, Inter_700Bold, Inter_800ExtraBold, JetBrainsMono_600SemiBold, JetBrainsMono_700Bold, NotoSansSinhala_400Regular, NotoSansSinhala_600SemiBold, NotoSansSinhala_700Bold, NotoSansSinhala_800ExtraBold, NotoSansTamil_600SemiBold, NotoSansTamil_700Bold, NotoSansTamil_800ExtraBold, PlusJakartaSans_700Bold, PlusJakartaSans_800ExtraBold };
