// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import Screen from '@/screens/sm-26-sign-in';

export const metadata: Metadata = { title: "SM-26 Sign in · Lodestar Store" };

const nav = {
  "links": {
    "L122": {
      "href": "/store/sm-02-deliveries",
      "kind": "go"
    },
    "L123": {
      "href": "/store/sm-35-reset-access",
      "kind": "go"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P1" nav={nav}>
      <Screen />
    </ScreenShell>
  );
}
