import type { Config } from 'jest';
import nextJest from 'next/jest.js';

// next/jest wires the Next.js compiler (SWC) transform, CSS/image/font mocks, .env loading and the
// tsconfig path alias. See node_modules/next/dist/docs/01-app/02-guides/testing/jest.md.
const createJestConfig = nextJest({ dir: './' });

const config: Config = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleNameMapper: { '^@/(.*)$': '<rootDir>/$1' },
  testMatch: ['<rootDir>/__tests__/**/*.test.{ts,tsx}', '<rootDir>/{app,components,lib}/**/*.test.{ts,tsx}'],
  testPathIgnorePatterns: ['/node_modules/', '<rootDir>/.next/', '<rootDir>/cypress/'],
  coverageProvider: 'v8',
  coverageDirectory: 'coverage',
  coverageReporters: ['lcov', 'text-summary', 'cobertura'],
  // Hand-written code only. The screens and their page.tsx wrappers are generated by tools/screengen.
  collectCoverageFrom: [
    'components/**/*.{ts,tsx}',
    'app/page.tsx',
    'lib/**/*.{ts,tsx}',
    'live/**/*.{ts,tsx}',
    '!**/*.d.ts',
  ],
  // JUnit XML for CI test results.
  reporters: process.env.CI
    ? ['default', ['jest-junit', { outputDirectory: 'reports/junit', outputName: 'jest.xml' }]]
    : ['default'],
};

export default createJestConfig(config);
