FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY prisma ./prisma
RUN npx prisma generate
CMD ["sh", "-c", "npx prisma migrate deploy && ([ \"$RUN_SEED\" = 'true' ] && npx ts-node prisma/seed.ts || true)"]
