// Writes the Next.js website from out/screens.json: every desktop screen as a page under
// frontend/app/<app>/<screen>/, using the design's own CSS (shared assets + each board's CSS, scoped).
// Usage: node gen-web.js   (after node extract.js)
const fs = require('fs');
const path = require('path');
const scopeCss = require('./cssscope');

const REPO = path.resolve(__dirname, '..', '..');
const FE = path.join(REPO, 'frontend');
const DATA = JSON.parse(fs.readFileSync(path.join(__dirname, 'out', 'screens.json'), 'utf8'));
const frames = DATA.frames;
const byKey = Object.fromEntries(frames.map(f => [f.key, f]));
const web = frames.filter(f => f.plat === 'desktop');
const FACE = { store: 'Lodestar Store', plan: 'Lodestar Plan', dock: 'Lodestar Dock', run: 'Lodestar Run', admin: 'Lodestar Admin' };
const HEADER = '// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.\n';

const url = f => `/${f.app}/${f.key}`;
const write = (p, s) => { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, s); };
const rm = p => fs.rmSync(p, { recursive: true, force: true });

// ---------- clean what this generator owns (and the old static copies it replaces)
// only folders this generator wrote (they carry its header); never anything written by hand
const mine = f => fs.existsSync(f) && fs.readFileSync(f, 'utf8').startsWith('// Generated by tools/screengen');
for (const app of ['store', 'plan', 'admin']) {
  const d = path.join(FE, 'app', app);
  if (!fs.existsSync(d)) continue;
  for (const sub of fs.readdirSync(d)) if (mine(path.join(d, sub, 'page.tsx'))) rm(path.join(d, sub));
}
const sdir = path.join(FE, 'screens');
if (fs.existsSync(sdir)) for (const f of fs.readdirSync(sdir)) if (mine(path.join(sdir, f))) rm(path.join(sdir, f));

// ---------- CSS: shared design assets + scoped board CSS
const ASSETS = path.join(REPO, 'Designing', 'assets');
const styles = path.join(FE, 'app', 'styles');
rm(path.join(styles, 'boards'));
for (const f of ['tokens.css', 'base.css', 'components.css', 'modern.css', 'ui2.css']) {
  const css = fs.readFileSync(path.join(ASSETS, f), 'utf8').replace(/@import\s+url\([^)]*\)\s*;?/g, '');
  write(path.join(styles, f), css);
}
const boards = [...new Set(web.map(f => f.board))];
for (const b of boards) {
  const file = fs.readdirSync(path.join(REPO, 'Designing', 'pages')).find(x => x.startsWith(b + '-'));
  const html = fs.readFileSync(path.join(REPO, 'Designing', 'pages', file), 'utf8');
  const css = [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map(m => m[1]).join('\n');
  write(path.join(styles, 'boards', b + '.css'), `/* ${file}: board CSS scoped to .b-${b} */\n` + scopeCss(css, '.b-' + b));
}
write(path.join(styles, 'web.css'), `/* The website shows each desktop screen full-window, without the design frame's bezel or browser bar. */
html, body { background: #EEF1F6; }
.web-screen { position: relative; width: 100vw; height: 100vh; overflow: auto; }
.web-screen > .frame {
  width: 100% !important; height: 100% !important; min-width: 1280px; min-height: 760px;
  border: 0 !important; border-radius: 0 !important; box-shadow: none !important; margin: 0;
}
/* overlays were placed under the design's 40px browser bar; the website has none */
.web-screen > .frame > .dx-scrim, .web-screen > .frame > .dx-drawer { top: 0 !important; }
.web-screen > .frame > .dx-modal { margin-top: -40px; left: 50% !important; transform: translateX(-50%); }
.web-screen [data-lk], .web-screen.is-tappable { cursor: pointer; }
.web-screen [data-lk]:focus-visible { outline: 3px solid #3B4CCA; outline-offset: 2px; }
.web-toast {
  position: fixed; left: 50%; bottom: 28px; transform: translateX(-50%); z-index: 1000;
  display: flex; align-items: center; gap: 12px; padding: 12px 18px; border-radius: 14px;
  background: #141B4D; color: #FFFFFF; font: 600 14px/1.4 Inter, system-ui, sans-serif; box-shadow: 0 12px 32px rgba(10,15,40,.28);
}
.web-toast b { color: #F5B83D; }
.web-toast button { margin-left: 8px; padding: 6px 12px; border: 0; border-radius: 999px; background: #F5B83D; color: #141B4D; font: 700 13px Inter, system-ui, sans-serif; cursor: pointer; }
`);
write(path.join(FE, 'app', 'globals.css'), `@import './styles/tokens.css';
@import './styles/base.css';
@import './styles/components.css';
@import './styles/modern.css';
@import './styles/ui2.css';
${boards.map(b => `@import './styles/boards/${b}.css';`).join('\n')}
@import './styles/web.css';
`);

// ---------- screen components
function linkTable(f) {
  const t = {};
  for (const [code, l] of Object.entries(f.links)) {
    if (!l.to) continue;
    const dest = byKey[l.to];
    if (!dest) continue;
    if (dest.plat !== 'desktop') t[code] = { app: FACE[dest.app], screen: dest.name, kind: l.kind };
    else t[code] = { href: url(dest), kind: l.kind };
  }
  const one = key => { const d = byKey[key]; if (!d) return undefined; return d.plat === 'desktop' ? { href: url(d) } : { app: FACE[d.app], screen: d.name }; };
  return { links: t, auto: f.auto ? one(f.auto) : undefined, whole: f.whole ? one(f.whole) : undefined };
}
const compName = k => 'Screen' + k.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join('').replace(/^(\d)/, '_$1');

for (const f of web) {
  const dir = path.join(FE, 'app', f.app, f.key);
  const table = linkTable(f);
  write(path.join(FE, 'screens', f.key + '.tsx'), `${HEADER}// ${f.name} (${f.board})
// @ts-nocheck
export default function ${compName(f.key)}() {
  return (
    ${f.jsx}
  );
}
`);
  write(path.join(dir, 'page.tsx'), `${HEADER}import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import Screen from '@/screens/${f.key}';

export const metadata: Metadata = { title: ${JSON.stringify(f.name.replace(/\s*·\s*desktop$/i, '') + ' · ' + FACE[f.app])} };

const nav = ${JSON.stringify(table, null, 2).replace(/\n/g, '\n')};

export default function Page() {
  return (
    <ScreenShell board="${f.board}" nav={nav}>
      <Screen />
    </ScreenShell>
  );
}
`);
}

// app landing routes: /store, /plan, /admin -> the face's first screen
const STARTS = { store: 'SM-26', plan: 'DSP-06', admin: 'ADM-01' };
for (const [app, id] of Object.entries(STARTS)) {
  const f = web.find(x => x.id === id) || web.find(x => x.app === app);
  write(path.join(FE, 'app', app, 'page.tsx'), `${HEADER}import { redirect } from 'next/navigation';

export default function Page() {
  redirect(${JSON.stringify(url(f))});
}
`);
}

// screen directory used by the home page
const dir = {};
for (const f of web) (dir[f.app] = dir[f.app] || []).push({ id: f.id, name: f.name.replace(/\s*·\s*desktop$/i, ''), href: url(f) });
write(path.join(FE, 'screens', 'index.ts'), `${HEADER}export type ScreenEntry = { id: string; name: string; href: string };
export const FACES: Record<string, { title: string; start: string; screens: ScreenEntry[] }> = ${JSON.stringify(
  Object.fromEntries(Object.entries(dir).map(([app, list]) => [app, { title: FACE[app], start: `/${app}`, screens: list }])), null, 2)};
export const FLOWS = ${JSON.stringify(DATA.starts.filter(s => { const f = frames.find(x => x.id === s[1] && (!s[2] || x.name.startsWith(s[2]))); return f && f.plat === 'desktop'; })
  .map(s => { const f = frames.find(x => x.id === s[1] && (!s[2] || x.name.startsWith(s[2]))); return { name: s[0], href: url(f) }; }), null, 2)};
`);
console.log(`web: ${web.length} screens, ${boards.length} board stylesheets`);
