apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: outlets
  labels:
    app: outlets
    app.kubernetes.io/name: outlets
    app.kubernetes.io/part-of: lodestar
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: outlets
