apiVersion: v1
kind: ServiceAccount
metadata:
  name: outlets
  labels:
    app: outlets
    app.kubernetes.io/name: outlets
    app.kubernetes.io/part-of: lodestar
  annotations:
    azure.workload.identity/client-id: CLIENT_ID_OUTLETS
    azure.workload.identity/tenant-id: TENANT_ID
automountServiceAccountToken: false
