// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import LiveSwitch from '@/components/live/LiveSwitch';
import Screen from '@/screens/sm-27-orders-and-history';
import Live from '@/live/sm-27-orders-and-history';

export const metadata: Metadata = { title: "SM-27 Orders & history · Lodestar Store" };

const nav = {
  "links": {
    "L131": {
      "href": "/store/sm-01-place-order",
      "kind": "go"
    },
    "L133": {
      "href": "/store/sm-28-receipts-and-credit-notes",
      "kind": "go"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P1" nav={nav} live>
      <LiveSwitch live={<Live />}>
        <Screen />
      </LiveSwitch>
    </ScreenShell>
  );
}
