apiVersion: v1
kind: Service
metadata:
  name: trips
  labels:
    app: trips
    app.kubernetes.io/name: trips
    app.kubernetes.io/part-of: lodestar
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
  - name: http
    port: 3006
    targetPort: http
    protocol: TCP
    appProtocol: http
