apiVersion: v1
kind: ServiceAccount
metadata:
  name: trips
  labels:
    app: trips
    app.kubernetes.io/name: trips
    app.kubernetes.io/part-of: lodestar
  annotations:
    azure.workload.identity/client-id: CLIENT_ID_TRIPS
    azure.workload.identity/tenant-id: TENANT_ID
automountServiceAccountToken: false
