apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  labels:
    app: notifications
    app.kubernetes.io/name: notifications
    app.kubernetes.io/part-of: lodestar
data:
  SERVICE_NAME: notifications
  PORT: '3008'
  DB_SCHEMA: notifications
  WS_PATH: /ws/
