apiVersion: v1
kind: ServiceAccount
metadata:
  name: notifications
  labels:
    app: notifications
    app.kubernetes.io/name: notifications
    app.kubernetes.io/part-of: lodestar
  annotations:
    azure.workload.identity/client-id: CLIENT_ID_NOTIFICATIONS
    azure.workload.identity/tenant-id: TENANT_ID
automountServiceAccountToken: false
