apiVersion: v1
kind: Service
metadata:
  name: notifications
  labels:
    app: notifications
    app.kubernetes.io/name: notifications
    app.kubernetes.io/part-of: lodestar
spec:
  type: ClusterIP
  selector:
    app: notifications
  ports:
  - name: http
    port: 3008
    targetPort: http
    protocol: TCP
    appProtocol: http
