// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import Screen from '@/screens/dsp-39-ask-the-planning-agent';

export const metadata: Metadata = { title: "DSP-39 Ask the planning agent · Lodestar Plan" };

const nav = {
  "links": {
    "L55": {
      "href": "/plan/dsp-40-agent-proposal-in-draft",
      "kind": "go"
    },
    "N0": {
      "href": "/plan/dsp-08-today-overview",
      "kind": "nav"
    },
    "N1": {
      "href": "/plan/dsp-01-cutoff-queue",
      "kind": "nav"
    },
    "N2": {
      "href": "/plan/dsp-02-plan-board",
      "kind": "nav"
    },
    "N3": {
      "href": "/plan/dsp-17-deferral-log",
      "kind": "nav"
    },
    "N4": {
      "href": "/plan/dsp-04-live-operations",
      "kind": "nav"
    },
    "N5": {
      "href": "/plan/dsp-13-exceptions-inbox",
      "kind": "nav"
    },
    "N6": {
      "href": "/plan/dsp-05-capacity-outlook",
      "kind": "nav"
    },
    "N7": {
      "href": "/plan/dsp-19-fleet-and-vehicle-profile",
      "kind": "nav"
    },
    "N8": {
      "href": "/plan/dsp-16-models-and-fallbacks",
      "kind": "nav"
    },
    "N9": {
      "href": "/plan/dsp-20-settings",
      "kind": "nav"
    },
    "C": {
      "href": "/plan/dsp-02-plan-board",
      "kind": "back"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P2" nav={nav}>
      <Screen />
    </ScreenShell>
  );
}
