apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  labels:
    app: orders
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: lodestar
data:
  SERVICE_NAME: orders
  PORT: '3002'
  DB_SCHEMA: orders
