apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: lodestar
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
  - name: http
    port: 3002
    targetPort: http
    protocol: TCP
    appProtocol: http
