apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sync
  labels:
    app: sync
    app.kubernetes.io/name: sync
    app.kubernetes.io/part-of: lodestar
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sync
