apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync
  labels:
    app: sync
    app.kubernetes.io/name: sync
    app.kubernetes.io/part-of: lodestar
  annotations:
    azure.workload.identity/client-id: CLIENT_ID_SYNC
    azure.workload.identity/tenant-id: TENANT_ID
automountServiceAccountToken: false
