apiVersion: v1
kind: Service
metadata:
  name: sync
  labels:
    app: sync
    app.kubernetes.io/name: sync
    app.kubernetes.io/part-of: lodestar
spec:
  type: ClusterIP
  selector:
    app: sync
  ports:
  - name: http
    port: 3007
    targetPort: http
    protocol: TCP
    appProtocol: http
