apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: audit
  labels:
    app: audit
    app.kubernetes.io/name: audit
    app.kubernetes.io/part-of: lodestar
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: audit
