apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit
  labels:
    app: audit
    app.kubernetes.io/name: audit
    app.kubernetes.io/part-of: lodestar
  annotations:
    azure.workload.identity/client-id: CLIENT_ID_AUDIT
    azure.workload.identity/tenant-id: TENANT_ID
automountServiceAccountToken: false
