// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import LiveSwitch from '@/components/live/LiveSwitch';
import Screen from '@/screens/sm-28-receipts-and-credit-notes';
import Live from '@/live/sm-28-receipts-and-credit-notes';

export const metadata: Metadata = { title: "SM-28 Receipts & credit notes · Lodestar Store" };

const nav = {
  "links": {
    "L135": {
      "href": "/store/sm-27-orders-and-history",
      "kind": "go"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P1" nav={nav} live>
      <LiveSwitch live={<Live />}>
        <Screen />
      </LiveSwitch>
    </ScreenShell>
  );
}
