// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
// DR-25 Connection banner states · phone components (P4, phone)
import { Text, View, StyleSheet } from 'react-native';
import { Frame, Icon, type ScreenNav } from '@/lodestar/runtime';

const nav: ScreenNav = {"links":{}};

export default function ScreenDr25ConnectionBannerStatesComponents() {
  return (
    <Frame bg="#070b16" nav={nav} style={s.v0}>
      <View style={s.v24}>
        <View style={s.v2}>
          <Text style={s.t1}>{"Connection banner"}</Text>
        </View>
        <View style={s.v6}>
          <View style={s.v4}>
            <Text style={s.t3}>{"3:41"}</Text>
          </View>
          <Text style={s.t5}>{"At the hub · run saved"}</Text>
        </View>
        <View style={s.v10}>
          <Icon xml={X0} width={20} height={20} style={s.v7} />
          <View style={s.v9}>
            <View>
              <Text style={s.t8}>{"Online · saved for offline 3:41"}</Text>
            </View>
          </View>
        </View>
        <View style={s.v6}>
          <View style={s.v4}>
            <Text style={s.t3}>{"4:38"}</Text>
          </View>
          <Text style={s.t5}>{"Signal lost above Ramboda"}</Text>
        </View>
        <View style={s.v13}>
          <Icon xml={X1} width={20} height={20} style={s.v7} />
          <View style={s.v9}>
            <View>
              <Text style={s.t11}>{"No signal · keep going"}</Text>
            </View>
            <View>
              <Text style={s.t12}>{"Your run is on this phone. Nothing is lost."}</Text>
            </View>
          </View>
        </View>
        <View style={s.v6}>
          <View style={s.v4}>
            <Text style={s.t3}>{"6:58"}</Text>
          </View>
          <Text style={s.t5}>{"Offline with records waiting"}</Text>
        </View>
        <View style={s.v13}>
          <Icon xml={X2} width={20} height={20} style={s.v7} />
          <View style={s.v9}>
            <View>
              <Text style={s.t11}>{"No signal since 4:38 · 4 waiting"}</Text>
            </View>
            <View>
              <Text style={s.t12}>{"They send by themselves when signal returns."}</Text>
            </View>
          </View>
        </View>
        <View style={s.v6}>
          <View style={s.v4}>
            <Text style={s.t3}>{"8:40"}</Text>
          </View>
          <Text style={s.t5}>{"Back online near Pussellawa"}</Text>
        </View>
        <View style={s.v15}>
          <Icon xml={X3} width={20} height={20} style={s.v7} />
          <View style={s.v9}>
            <View>
              <Text style={s.t14}>{"Back online · sending 3 of 7"}</Text>
            </View>
            <View>
              <Text style={s.t12}>{"Text first, photos last."}</Text>
            </View>
          </View>
        </View>
        <View style={s.v6}>
          <View style={s.v4}>
            <Text style={s.t3}>{"8:42"}</Text>
          </View>
          <Text style={s.t5}>{"Everything sent"}</Text>
        </View>
        <View style={s.v10}>
          <Icon xml={X0} width={20} height={20} style={s.v7} />
          <View style={s.v9}>
            <View>
              <Text style={s.t8}>{"All 7 records synced"}</Text>
            </View>
          </View>
        </View>
        <View style={s.v6}>
          <Text style={s.t5}>{"Matching nav pills"}</Text>
        </View>
        <View style={s.v23}>
          <View style={s.v18}>
            <Icon xml={X4} width={14} height={14} style={s.v16} />
            <Text style={s.t17} numberOfLines={1}>{"Offline-ready"}</Text>
          </View>
          <View style={s.v20}>
            <Icon xml={X5} width={14} height={14} style={s.v16} />
            <Text style={s.t19} numberOfLines={1}>{"Saved on phone"}</Text>
          </View>
          <View style={s.v20}>
            <Icon xml={X5} width={14} height={14} style={s.v16} />
            <Text style={s.t19} numberOfLines={1}>{"4 waiting"}</Text>
          </View>
          <View style={s.v22}>
            <Icon xml={X6} width={14} height={14} style={s.v16} />
            <Text style={s.t21} numberOfLines={1}>{"Sending"}</Text>
          </View>
          <View style={s.v18}>
            <Icon xml={X4} width={14} height={14} style={s.v16} />
            <Text style={s.t17} numberOfLines={1}>{"Synced 8:40"}</Text>
          </View>
        </View>
      </View>
    </Frame>
  );
}

const X0 = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#5ee0a8\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 6 9 17l-5-5\" fill=\"none\" stroke=\"#5ee0a8\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></path></svg>";
const X1 = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#d6cfc7\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M12 20h.01M8.5 16.43a5 5 0 0 1 7 0M2 8.82a15 15 0 0 1 4.17-2.65M10.66 5c4.01-.36 8.14.9 11.34 3.76M16.85 11.25a10 10 0 0 1 2.22 1.68M5 13a10 10 0 0 1 5.24-2.76M2 2l20 20\" fill=\"none\" stroke=\"#d6cfc7\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></path></svg>";
const X2 = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#d6cfc7\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"none\" stroke=\"#d6cfc7\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></circle><path d=\"M12 6v6l4 2\" fill=\"none\" stroke=\"#d6cfc7\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></path></svg>";
const X3 = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#6cc4f5\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\" width=\"20\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M21 12a9 9 0 1 1-3-6.7L21 8\" fill=\"none\" stroke=\"#6cc4f5\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></path><path d=\"M21 3v5h-5\" fill=\"none\" stroke=\"#6cc4f5\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></path></svg>";
const X4 = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#5ee0a8\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\" width=\"14\" height=\"14\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 6 9 17l-5-5\" fill=\"none\" stroke=\"#5ee0a8\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></path></svg>";
const X5 = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#d6cfc7\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\" width=\"14\" height=\"14\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M12 20h.01M8.5 16.43a5 5 0 0 1 7 0M2 8.82a15 15 0 0 1 4.17-2.65M10.66 5c4.01-.36 8.14.9 11.34 3.76M16.85 11.25a10 10 0 0 1 2.22 1.68M5 13a10 10 0 0 1 5.24-2.76M2 2l20 20\" fill=\"none\" stroke=\"#d6cfc7\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></path></svg>";
const X6 = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#6cc4f5\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\" width=\"14\" height=\"14\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M21 12a9 9 0 1 1-3-6.7L21 8\" fill=\"none\" stroke=\"#6cc4f5\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></path><path d=\"M21 3v5h-5\" fill=\"none\" stroke=\"#6cc4f5\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill-opacity=\"1\" stroke-opacity=\"1\" fill-rule=\"nonzero\"></path></svg>";

const s = StyleSheet.create({
  v0: {"flexDirection":"column","alignItems":"stretch","backgroundColor":"#070b16","flex":1},
  t1: {"color":"#f2f4fa","fontSize":22,"lineHeight":33,"letterSpacing":-0.4,"fontFamily":"PlusJakartaSans_800ExtraBold"},
  v2: {"paddingRight":20,"paddingBottom":4,"paddingLeft":20},
  t3: {"color":"#ffcb5c","fontSize":13,"lineHeight":19.5,"fontFamily":"JetBrainsMono_700Bold"},
  v4: {"flexShrink":1},
  t5: {"color":"#7f89a3","fontSize":13,"lineHeight":19.5,"fontFamily":"Inter_700Bold"},
  v6: {"flexDirection":"row","alignItems":"center","rowGap":8,"columnGap":8,"paddingTop":6,"paddingRight":20,"paddingLeft":20},
  v7: {"flexShrink":0,"marginTop":1,"overflow":"hidden"},
  t8: {"color":"#5ee0a8","fontSize":14,"lineHeight":20.3,"fontFamily":"Inter_700Bold"},
  v9: {"flexDirection":"column","alignItems":"stretch","rowGap":2,"columnGap":2,"flexShrink":1},
  v10: {"flexDirection":"row","alignItems":"flex-start","rowGap":12,"columnGap":12,"paddingTop":14,"paddingRight":16,"marginRight":16,"paddingBottom":14,"paddingLeft":16,"marginLeft":16,"backgroundColor":"#0d2a20","borderRadius":18},
  t11: {"color":"#d6cfc7","fontSize":14,"lineHeight":20.3,"fontFamily":"Inter_700Bold"},
  t12: {"color":"#b5bdd1","fontSize":14,"lineHeight":20.3,"fontFamily":"Inter_400Regular"},
  v13: {"flexDirection":"row","alignItems":"flex-start","rowGap":12,"columnGap":12,"paddingTop":14,"paddingRight":16,"marginRight":16,"paddingBottom":14,"paddingLeft":16,"marginLeft":16,"borderWidth":1,"borderColor":"#57534e","borderStyle":"dashed","borderRadius":18},
  t14: {"color":"#6cc4f5","fontSize":14,"lineHeight":20.3,"fontFamily":"Inter_700Bold"},
  v15: {"flexDirection":"row","alignItems":"flex-start","rowGap":12,"columnGap":12,"paddingTop":14,"paddingRight":16,"marginRight":16,"paddingBottom":14,"paddingLeft":16,"marginLeft":16,"backgroundColor":"#0b2233","borderRadius":18},
  v16: {"flexShrink":0,"overflow":"hidden"},
  t17: {"color":"#5ee0a8","fontSize":13,"lineHeight":19.5,"fontFamily":"Inter_700Bold"},
  v18: {"flexDirection":"row","alignItems":"center","rowGap":6,"columnGap":6,"flexShrink":1,"paddingRight":12,"paddingLeft":12,"height":28,"backgroundColor":"#0d2a20","borderRadius":14},
  t19: {"color":"#d6cfc7","fontSize":13,"lineHeight":19.5,"fontFamily":"Inter_700Bold"},
  v20: {"flexDirection":"row","alignItems":"center","rowGap":6,"columnGap":6,"flexShrink":1,"paddingRight":12,"paddingLeft":12,"height":28,"borderWidth":1,"borderColor":"#57534e","borderStyle":"dashed","borderRadius":14},
  t21: {"color":"#6cc4f5","fontSize":13,"lineHeight":19.5,"fontFamily":"Inter_700Bold"},
  v22: {"flexDirection":"row","alignItems":"center","rowGap":6,"columnGap":6,"flexShrink":1,"paddingRight":12,"paddingLeft":12,"height":28,"backgroundColor":"#0b2233","borderRadius":14},
  v23: {"flexDirection":"row","flexWrap":"wrap","alignItems":"stretch","rowGap":8,"columnGap":8,"paddingRight":16,"paddingLeft":16},
  v24: {"flexDirection":"column","alignItems":"stretch","rowGap":12,"columnGap":12,"paddingTop":22,"paddingBottom":24},
});
