apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- peer-authentication.yaml
- request-authentication.yaml
- authz-deny-all.yaml
- authz-allow.yaml
- gateway.yaml
- virtualservices.yaml
- destinationrules.yaml
namespace: lodestar
