// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import Screen from '@/screens/adm-04-add-or-edit-person';

export const metadata: Metadata = { title: "ADM-04 Add or edit person · Lodestar Admin" };

const nav = {
  "links": {
    "L290": {
      "href": "/admin/adm-03-people-and-roles",
      "kind": "go"
    },
    "C": {
      "href": "/admin/adm-03-people-and-roles",
      "kind": "back"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P6" nav={nav}>
      <Screen />
    </ScreenShell>
  );
}
