// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import { redirect } from 'next/navigation';

export default function Page() {
  redirect("/plan/dsp-06-sign-in");
}
