// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import FaceLanding from '@/components/live/FaceLanding';

export default function Page() {
  return <FaceLanding signIn="/plan/dsp-06-sign-in" home="/plan/dsp-08-today-overview" />;
}
