// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import Screen from '@/screens/dsp-09-order-detail-drawer';

export const metadata: Metadata = { title: "DSP-09 Order detail drawer · Lodestar Plan" };

const nav = {
  "links": {
    "L153": {
      "href": "/plan/dsp-02-plan-board",
      "kind": "go"
    },
    "L154": {
      "href": "/plan/dsp-18-outlet-profile",
      "kind": "go"
    },
    "C": {
      "href": "/plan/dsp-01-cutoff-queue",
      "kind": "back"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P2" nav={nav}>
      <Screen />
    </ScreenShell>
  );
}
