/// <reference types="cypress" />
// Custom commands for the Lodestar desk screens (Store desk, Plan, Admin).
// A screen is generated by tools/screengen and wrapped in components/ScreenShell.tsx, which makes every
// element marked `data-lk="<code>"` navigate like the Figma prototype.
//
// Two modes:
//  - Design preview (the click-through and the demo flows): openScreen() turns on the static prototype for the
//    tab (sessionStorage "lodestar.design"), so no sign-in and no API are needed.
//  - Live (cypress/e2e/live, CYPRESS_LIVE=1, against the stack): loginAs() signs in through Keycloak once per
//    persona (cy.session caches the tab's sessionStorage, where the OIDC tokens live) and openLive() visits a
//    screen with the preview off.

export type Persona = 'dispatcher' | 'store' | 'admin';

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    interface Chainable {
      /** Visit a screen as if opened directly (no same-site referrer), and wait for React to hydrate it. */
      openScreen(path: string, opts?: { freezeTimers?: boolean }): Chainable<void>;
      /** Wait until ScreenShell has hydrated, so its click handler is live. */
      waitForHydration(): Chainable<void>;
      /** Click the design element with this data-lk code. `text`, when given, must appear in it (case-insensitive). */
      tapLink(code: string, text?: string): Chainable<void>;
      /** Assert the current path. */
      shouldBeOn(path: string): Chainable<void>;
      /** Assert the "Continues in <app> on the phone" notice, and that the page did not navigate. */
      shouldContinueOnPhone(app?: string, screen?: string): Chainable<void>;
      /** Live mode: sign in through Keycloak as a persona (cached per persona with cy.session). */
      loginAs(persona: Persona): Chainable<void>;
      /** Live mode: open a screen with real data (design preview off) and wait until it rendered. */
      openLive(path: string): Chainable<void>;
    }
  }
}

// Cypress injects its driver <script> into the AUT's <head>. The app renders <head> itself (app/layout.tsx), so
// React reports a hydration mismatch (#418/#423/#425) that only exists under Cypress: the same pages hydrate
// cleanly in a normal browser, which tests/e2e/specs/ui/web-smoke.spec.ts ("no page errors") checks.
// React recovers by client-rendering, so the click-through is unaffected. Every other app error still fails.
const HARNESS_NOISE = [/ResizeObserver loop/, /Minified React error #(418|423|425)\b/, /Hydration failed/];
Cypress.on('uncaught:exception', err => !HARNESS_NOISE.some(re => re.test(err.message)));

Cypress.Commands.add('openScreen', (path: string, opts: { freezeTimers?: boolean } = {}) => {
  if (opts.freezeTimers) cy.clock(Date.now(), ['setTimeout', 'clearTimeout']);
  cy.visit(path, {
    onBeforeLoad(win) {
      // The Cypress runner is served from the same origin as the app, so the AUT's referrer would look
      // same-site and "back" links would call history.back(). Model a user opening the URL directly.
      Object.defineProperty(win.document, 'referrer', { get: () => '', configurable: true });
      // The click-through checks the design prototype: no sign-in, no API (frontend/lib/mode.ts).
      win.sessionStorage.setItem('lodestar.design', '1');
    },
  });
  cy.waitForHydration();
});

Cypress.Commands.add('waitForHydration', () => {
  // React tags every hydrated DOM node with a `__reactFiber$…` expando; before that, clicks do nothing.
  cy.get('.web-screen', { timeout: 30_000 }).should($el => {
    const hydrated = Object.keys($el[0]).some(k => k.startsWith('__reactFiber$') || k.startsWith('__reactProps$'));
    if (!hydrated) throw new Error('screen not hydrated yet');
  });
});

Cypress.Commands.add('tapLink', (code: string, text?: string) => {
  const el = cy.get(`.web-screen [data-lk="${code}"]`).first();
  if (text) el.should($e => {
    const t = $e.text().replace(/\s+/g, ' ');
    if (!t.toLowerCase().includes(text.toLowerCase())) throw new Error(`[data-lk=${code}] text "${t.slice(0, 80)}" does not contain "${text}"`);
  });
  cy.get(`.web-screen [data-lk="${code}"]`).first().scrollIntoView({ offset: { top: -200, left: 0 } }).click();
});

Cypress.Commands.add('shouldBeOn', (path: string) => {
  cy.location('pathname', { timeout: 20_000 }).should('eq', path);
  cy.get('.web-screen', { timeout: 30_000 }).should('exist');
});

Cypress.Commands.add('shouldContinueOnPhone', (app?: string, screen?: string) => {
  cy.location('pathname').then(before => {
    cy.get('.web-toast[role="status"]', { timeout: 5_000 })
      .should('contain.text', 'Continues in')
      .and('contain.text', app ?? '')
      .and('contain.text', screen ?? '');
    cy.location('pathname').should('eq', before);
  });
});

// ---------------------------------------------------------------- live mode (Keycloak + the real API)

const FACE: Record<Persona, { face: string; signIn: string; user: string; passwordKey: string; fallback: string }> = {
  dispatcher: { face: 'plan', signIn: '/plan/dsp-06-sign-in', user: 'nilanthi', passwordKey: 'LODESTAR_PASSWORD', fallback: 'lodestar-dev-only' },
  store: { face: 'store', signIn: '/store/sm-26-sign-in', user: 'fathima', passwordKey: 'LODESTAR_PASSWORD', fallback: 'lodestar-dev-only' },
  admin: { face: 'admin', signIn: '/admin/adm-01-sign-in', user: 'admin', passwordKey: 'LODESTAR_ADMIN_PASSWORD', fallback: 'lodestar-admin-dev-only' },
};

Cypress.Commands.add('loginAs', (persona: Persona) => {
  const p = FACE[persona];
  const users = (Cypress.expose('users') ?? {}) as Partial<Record<Persona, string>>;
  const username = users[persona] ?? p.user;
  cy.env([p.passwordKey]).then(env => {
    const password = String(env[p.passwordKey] ?? p.fallback);
    cy.session(
      ['lodestar', persona, username],
      () => {
        cy.visit(`${p.signIn}?design=0`);
        cy.get('[data-testid="sign-in"]', { timeout: 30_000 }).should('contain.text', 'Continue to sign in').click();
        const app = new URL(Cypress.config('baseUrl')!).origin;
        const idp = String(Cypress.expose('keycloakOrigin') || app);
        const fill = ({ u, pw }: { u: string; pw: string }) => {
          cy.get('#username', { timeout: 30_000 }).clear().type(u);
          cy.get('#password').type(pw, { log: false });
          cy.get('#kc-login').click();
        };
        // Through the gateway Keycloak is same-origin (/auth); a separate identity origin needs cy.origin.
        if (new URL(idp).origin === app) fill({ u: username, pw: password });
        else cy.origin(idp, { args: { u: username, pw: password } }, ({ u, pw }) => {
          cy.get('#username', { timeout: 30_000 }).clear().type(u);
          cy.get('#password').type(pw, { log: false });
          cy.get('#kc-login').click();
        });
        cy.location('pathname', { timeout: 30_000 }).should('match', new RegExp(`^/${p.face}/`));
      },
      {
        cacheAcrossSpecs: true,
        validate() {
          cy.window().then(win => {
            expect(Object.keys(win.sessionStorage).some(k => k.startsWith('oidc.user:')), 'OIDC session in sessionStorage').to.eq(true);
            expect(Object.keys(win.localStorage).some(k => k.startsWith('oidc.')), 'no tokens in localStorage').to.eq(false);
          });
        },
      },
    );
  });
});

Cypress.Commands.add('openLive', (path: string) => {
  cy.visit(path.includes('?') ? `${path}&design=0` : `${path}?design=0`);
  cy.get('.web-screen .frame', { timeout: 30_000 }).should('exist');
  cy.waitForHydration();
});
