apiVersion: v1
kind: Service
metadata:
  name: fleet
  labels:
    app: fleet
    app.kubernetes.io/name: fleet
    app.kubernetes.io/part-of: lodestar
spec:
  type: ClusterIP
  selector:
    app: fleet
  ports:
  - name: http
    port: 3004
    targetPort: http
    protocol: TCP
    appProtocol: http
