apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet
  labels:
    app: fleet
    app.kubernetes.io/name: fleet
    app.kubernetes.io/part-of: lodestar
  annotations:
    azure.workload.identity/client-id: CLIENT_ID_FLEET
    azure.workload.identity/tenant-id: TENANT_ID
automountServiceAccountToken: false
