apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  labels:
    app: agent
    app.kubernetes.io/name: agent
    app.kubernetes.io/part-of: lodestar
data:
  SERVICE_NAME: agent
  PORT: '8000'
  DB_SCHEMA: agent
  AGENT_MODEL: mock
  CHECKPOINT_SCHEMA: agent
  UVICORN_WORKERS: '2'
  PYTHONUNBUFFERED: '1'
