apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agent
  labels:
    app: agent
    app.kubernetes.io/name: agent
    app.kubernetes.io/part-of: lodestar
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: agent
