apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  labels:
    app: agent
    app.kubernetes.io/name: agent
    app.kubernetes.io/part-of: lodestar
  annotations:
    azure.workload.identity/client-id: CLIENT_ID_AGENT
    azure.workload.identity/tenant-id: TENANT_ID
automountServiceAccountToken: false
