apiVersion: v1
kind: Service
metadata:
  name: agent
  labels:
    app: agent
    app.kubernetes.io/name: agent
    app.kubernetes.io/part-of: lodestar
spec:
  type: ClusterIP
  selector:
    app: agent
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
    appProtocol: http
