// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import Screen from '@/screens/sm-02-deliveries';

export const metadata: Metadata = { title: "SM-02 Deliveries · Lodestar Store" };

const nav = {
  "links": {
    "L124": {
      "href": "/store/sm-01-place-order",
      "kind": "go"
    },
    "L125": {
      "href": "/store/sm-27-orders-and-history",
      "kind": "go"
    },
    "L128": {
      "href": "/store/sm-30-settings",
      "kind": "go"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P1" nav={nav}>
      <Screen />
    </ScreenShell>
  );
}
