// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import LiveSwitch from '@/components/live/LiveSwitch';
import Screen from '@/screens/adm-09-edit-outlet';
import Live from '@/live/adm-09-edit-outlet';

export const metadata: Metadata = { title: "ADM-09 Edit outlet · Lodestar Admin" };

const nav = {
  "links": {
    "L296": {
      "href": "/admin/adm-08-outlets",
      "kind": "go"
    },
    "C": {
      "href": "/admin/adm-08-outlets",
      "kind": "back"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P6" nav={nav} live>
      <LiveSwitch live={<Live />}>
        <Screen />
      </LiveSwitch>
    </ScreenShell>
  );
}
