// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import Screen from '@/screens/dsp-35-session-expired';

export const metadata: Metadata = { title: "DSP-35 Session expired · Lodestar Plan" };

const nav = {
  "links": {
    "L176": {
      "href": "/plan/dsp-02-plan-board",
      "kind": "go"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P2" nav={nav}>
      <Screen />
    </ScreenShell>
  );
}
