apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: lodestar
data:
  SERVICE_NAME: frontend
  PORT: '3000'
  HOSTNAME: 0.0.0.0
  NEXT_TELEMETRY_DISABLED: '1'
