apiVersion: v1
kind: Service
metadata:
  name: mobile-web
  labels:
    app: mobile-web
    app.kubernetes.io/name: mobile-web
    app.kubernetes.io/part-of: lodestar
spec:
  type: ClusterIP
  selector:
    app: mobile-web
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
    appProtocol: http
