apiVersion: v1
kind: ServiceAccount
metadata:
  name: mobile-web
  labels:
    app: mobile-web
    app.kubernetes.io/name: mobile-web
    app.kubernetes.io/part-of: lodestar
automountServiceAccountToken: false
