// Generated by tools/screengen from Designing/pages. Do not edit by hand: change the design and run `npm run screens` in tools/screengen.
import type { Metadata } from 'next';
import ScreenShell from '@/components/ScreenShell';
import Screen from '@/screens/adm-08-outlets';

export const metadata: Metadata = { title: "ADM-08 Outlets · Lodestar Admin" };

const nav = {
  "links": {
    "L294": {
      "href": "/admin/adm-09-edit-outlet",
      "kind": "go"
    },
    "L295": {
      "href": "/admin/adm-14-data-imports",
      "kind": "go"
    },
    "N0": {
      "href": "/admin/adm-02-overview",
      "kind": "nav"
    },
    "N1": {
      "href": "/admin/adm-05-access-requests",
      "kind": "nav"
    },
    "N2": {
      "href": "/admin/adm-03-people-and-roles",
      "kind": "nav"
    },
    "N3": {
      "href": "/admin/adm-06-devices",
      "kind": "nav"
    },
    "N5": {
      "href": "/admin/adm-10-vehicles",
      "kind": "nav"
    },
    "N6": {
      "href": "/admin/adm-12-operating-rules",
      "kind": "nav"
    },
    "N7": {
      "href": "/admin/adm-13-calendar",
      "kind": "nav"
    },
    "N8": {
      "href": "/admin/adm-14-data-imports",
      "kind": "nav"
    },
    "N9": {
      "href": "/admin/adm-16-audit-log",
      "kind": "nav"
    },
    "N10": {
      "href": "/admin/adm-17-planning-agent-guardrails",
      "kind": "nav"
    },
    "N11": {
      "href": "/admin/adm-18-notifications-and-integrations",
      "kind": "nav"
    }
  }
};

export default function Page() {
  return (
    <ScreenShell board="P6" nav={nav}>
      <Screen />
    </ScreenShell>
  );
}
